#!/bin/sh

rm -rf configure
rm -rf autom4te.cache/ 
rm -f config.log config.status 

rm -f src/*.o src/*.so src/*.dylib 

rm -rf inst/
mkdir inst

rm -rf windows/

cd src/proj
if test -e "Makefile"; then
  make clean
fi
