#!/bin/sh

rm -rf configure
rm -rf autom4te.cache/ 
rm -f config.log config.status 

rm -f src/Makevars 
rm -f src/*.o src/*.so src/*.dylib 

rm -f *.zip

rm -rf inst/include
rm -rf inst/share
rm -rf inst/lib
rm -rf inst/bin
rm -rf proj*/

rm -rf windows/

tools/prepare

autoconf