// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// proj_version
Rcpp::IntegerVector proj_version();
RcppExport SEXP libproj_proj_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(proj_version());
    return rcpp_result_gen;
END_RCPP
}
// test_api
Rcpp::NumericMatrix test_api(Rcpp::NumericMatrix lat_long);
RcppExport SEXP libproj_test_api(SEXP lat_longSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lat_long(lat_longSEXP);
    rcpp_result_gen = Rcpp::wrap(test_api(lat_long));
    return rcpp_result_gen;
END_RCPP
}
