# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proj_version <- function() {
    .Call('_libproj_proj_version', PACKAGE = 'libproj')
}

test_api <- function(lat_long) {
    .Call('_libproj_test_api', PACKAGE = 'libproj', lat_long)
}

